#version: "3.0"

volumes:
  db-data:
    external: false

services:

  db:

    image: mariadb:11.2
    #image: mariadb:11.6
    #image: mariadb:10.4.30

    container_name: mariadb

    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme
    volumes:
      - /srv/stevetest/mariadb/logs:/var/log/mysql
      - /srv/stevetest/mariadb/config:/etc/mysql/conf.d
      - /srv/stevetest/mariadb/data/databases:/var/lib/mysql

  app:
    restart: unless-stopped
    build: .
    links:
      - "db:mariadb"
    volumes:
      - .:/code
    ports:
      - "8180:8180"
      - "8443:8443"
    depends_on:
      - db
    
